name: prettier_reg_exp
description: "Create and manage regular expressions with ease, including predefined patterns, length constraints, and more."
version: 1.0.0
homepage: https://github.com/Hwassef/prettier_reg_exp

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter: